config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :signups

  root  'home#index'

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @signup = Signup.new
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :set_signup, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /signups
  # GET /signups.json
  def index
    @signups = Signup.paginate(:page => params[:page], :per_page => 3)
    
      #Post.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
  end

  # GET /signups/new
  def new
    @signup = Signup.new
  end

  # GET /signups/1/edit
  def edit
  end

  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(signup_params)

    respond_to do |format|
      if @signup.save
        format.html { redirect_to root_path, notice: 'Signup was successfully created.' }
        format.json { render :show, status: :created, location: @signup }
      else
        format.html { render :new }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signups/1
  # PATCH/PUT /signups/1.json
  def update
    respond_to do |format|
      if @signup.update(signup_params)
        format.html { redirect_to @signup, notice: 'Signup was successfully updated.' }
        format.json { render :show, status: :ok, location: @signup }
      else
        format.html { render :edit }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup.destroy
    respond_to do |format|
      format.html { redirect_to signups_url, notice: 'Signup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signup
      @signup = Signup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signup_params
      params.require(:signup).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
		<meta charset="UTF-8">
		<title>GH Calligraphy</title>
		<link rel="stylesheet" href="main.css">
</head>
<body>

	<div class="container">
		<div class="secondheader">
			<h2>Calligraphy</h2>
		</div>
		<div class="paragraph">
				<%= image_tag 'calligraphy-menu.jpg' %>
			<p>Lorizzle ipsizzle boofron sheezy amizzle, sure adipiscing pimpin'. Nullizzle yippiyo get down get down, aliquet volutpizzle, dope quis, gravida vel, fo shizzle. Pellentesque mammasay mammasa mamma oo sa fo shizzle mah nizzle fo rizzle, mah home g-dizzle. Fo shizzle erizzle. Dang at dolor dapibizzle turpizzle tempizzle shiz. Maurizzle pellentesque nibh izzle turpizzle. My shizz in boofron. Pellentesque sizzle sure crazy. In hac habitasse platea dope. Bow wow wow dapibus. Curabitizzle tellus you son of a bizzle, pretizzle pot, ma nizzle ac, dawg vitae, nunc. Fo shizzle my nizzle suscipizzle. Integer sempizzle velit sizzle .</p>
		</div>
		<div class="secondheader">
			<h2>About Grace Helmer</h2>
		</div>
		<div class="paragraph">
			<%= image_tag 'profile.png' %>
			<p>Lorizzle ipsizzle boofron sheezy amizzle, sure adipiscing pimpin'. Nullizzle yippiyo get down get down, aliquet volutpizzle, dope quis, gravida vel, fo shizzle. Pellentesque mammasay mammasa mamma oo sa fo shizzle mah nizzle fo rizzle, mah home g-dizzle. Fo shizzle erizzle. Dang at dolor dapibizzle turpizzle tempizzle shiz. Maurizzle pellentesque nibh izzle turpizzle. My shizz in boofron. Pellentesque sizzle sure crazy. In hac habitasse platea dope. Bow wow wow dapibus. Curabitizzle tellus you son of a bizzle, pretizzle pot, ma nizzle ac, dawg vitae, nunc. Fo shizzle my nizzle suscipizzle. Integer sempizzle velit sizzle .</p>
		</div>
</body>
</html>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
      	<%= render 'signups/form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

		<title>GH Calligraphy</title>
		<link rel="stylesheet" href="main.css">
		
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
    <link href='http://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
 
  <%= csrf_meta_tags %>
		<meta charset="UTF-8">
		
</head>

<body>
	<div class="header">
		<h1>GH Calligraphy</h1>
		<% if current_user %>
		  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>  
		  <% else %>
		  <%= link_to('Sign In', new_user_session_path) %> |
		  <%= link_to('Register', new_user_registration_path) %>
		  <% end %>
	</div>
	<div class="container">
		<div id="nav">
			<ul>
				<li><a href="http://www.google.com">Home</a></li>
				<li><a href="http://www.google.com">Calligraphy</a></li>
				<li><a href="http://www.google.com">Grace Helmer</a></li>
			</ul>
		</div>
	</div>
	<div class="headerimage">
  <% if notice %>
  <p class="notice"><%= notice %></p>
  <% end %>
  
  <% if alert %>
   <p class="alert"><%= alert %></p>
  <% end %>
  </div>
  <div class="container">
<%= yield %>
</div>
</body>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Learn More
</button>

	<div id="footer">
		<ul>
			<li>email: gracebhelmer@gmail.com</li>
			<li>1100 Howell Mill Road Unit 411  Atlanta, Georgia 30318</li>
		</ul>
	</div>
</html>

app/views/signups/_form.html.erb
<%= form_for(@signup) do |f| %>
  <% if @signup.errors.any? %>
    <div id="error_explanation">
      
      <h2><%= pluralize(@signup.errors.count, "error") %> prohibited this signup from being saved:</h2>

      <ul>
      <% @signup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Submit', class: "btn btn-default" %>
  </div>
<% end %>

app/views/signups/edit.html.erb
<h1>Editing signup</h1>

<%= render 'form' %>

<%= link_to 'Show', @signup %> |
<%= link_to 'Back', signups_path %>

app/views/signups/index.html.erb
<h1>Listing signups</h1>

<<div class="table-responsive">
  <table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @signups.each do |signup| %>
      <tr>
        <td><%= signup.first_name %></td>
        <td><%= signup.last_name %></td>
        <td><%= signup.email %></td>
        <td><%= link_to 'Show', signup %></td>
        <td><%= link_to 'Edit', edit_signup_path(signup) %></td>
        <td><%= link_to 'Destroy', signup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @posts %>
<br>


<%= link_to 'New Signup', new_signup_path %>

</div>

app/views/signups/new.html.erb
<h1>New signup</h1>

<%= render 'form' %>

<%= link_to 'Back', signups_path %>

app/views/signups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @signup.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @signup.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @signup.email %>
</p>

<%= link_to 'Edit', edit_signup_path(@signup) %> |
<%= link_to 'Back', signups_path %>